### ISSUE TITLE
组合模式的bug

### ISSUE THREAD

**Issue by FynnJason** [dkzwm/FormatEditText#1]
<me.dkzwm.widget.fet.FormattedEditText
        android:id="@+id/et_mobile_3"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="手机号特殊组合方式隔开"
        android:maxLines="1"
        app:fet_formatStyle="+(86)-***-****-****"
        app:fet_mark="*"
        app:fet_mode="mode_complex" />

当app:fet_formatStyle将86默认配置时，输入框将不能输入6和8

**Comment by FynnJason** [comment]
需求建议：能够提供对外的一个方法，只获取实际输入内容。
例如在简单模式中，我们输入手机号，实际从EditText.getText().toString()获取到的字符串是有空格的，我们在最后取值时还需要自己再替换掉空格，同理设置简单模式的其他符号或者组合模式的其他字符都会出现这个问题。

**Comment by dkzwm** [comment]
不好意思，我最近在休陪产假，这边暂时没办法实现这种需求，大概下周我能着手实现。

**Comment by dkzwm** [comment]
@FynnJason 你更新下0.0.7版本，问题应该修复了，同时获取实际输入内容的方法已提供：`getRealText()`。

**Comment by FynnJason** [comment]
已测试，没有问题
