### ISSUE TITLE
能不能有小数模式，即小数点

### ISSUE THREAD

**Issue by LLQQHH** [dkzwm/FormatEditText#3]

**Comment by dkzwm** [comment]
你的意思是输入金额？这边暂时没有支持这种需求。

**Comment by LLQQHH** [comment]
你这个容易改吗？现在是需要输入金额格式化的功能

**Comment by dkzwm** [comment]
输入金额这种场景改起来比较复杂了，牵涉到有小数点的问题，输入的是小数位还是整数位这些逻辑，场景会比较多。

**Comment by LLQQHH** [comment]
这可如何是好！！！

**Comment by dkzwm** [comment]
如果小数点是默认显示的，可以用两个输入框来做，前面的整数位用fet来实现，只是为了适配首位0的情况需要修改下fet源码，后面的小数位用edittext就行。

**Comment by LLQQHH** [comment]
我自己想办法把，两个输入框产品是不可能允许的，或者要吊我说你看ios可以，你为啥不行

**Comment by dkzwm** [comment]
@LLQQHH 大兄弟，这边实现了数字/金额格式化，你看是否有需要，可以切换到本库的`develop`分支，查看相关介绍，你也可以切换到develop分支，下载demo.apk或clone代码，运行demo进行测试。

**Comment by dkzwm** [comment]
@LLQQHH 已提交主分支，可以用了
