### ISSUE TITLE
databinding双向绑定数据 有问题

### ISSUE THREAD

**Issue by yxyaxng** [dkzwm/FormatEditText#4]

**Comment by dkzwm** [comment]
能否详细描述下问题，光你这个标题难以知道具体问题出在哪里，最好能贴出错误日志，这边没有测试过DataBinding，但考虑到xml和代码配置均验证没有问题，是否是你配置的数据有问题，例如格式不正确？这边只有待周一我抽空测试验证下

**Comment by dkzwm** [comment]
@yxyaxng 我测了下，这边建议使用事件绑定，绑定`afterTextChanged`事件获取text数据，由于格式化是发生在通知`onTextChanged`事件回调后的，所以获取到的数据是未进行格式化的数据，同时考虑到格式化后`onTextChanged`事件传递的参数可能已无法和格式化后数据一一对应，故而是先通知TextWatchers的`onTextChanged`事件回调。
